name: Java CI

# Trigger the workflow on push or pull request to the repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Java (you can specify the version here, Java 11 is used in this example)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'actions/setup-java' documentation for other distributions
        java-version: '11'

    # Step 3: Compile the Java code
    - name: Compile Java code
      run: javac stringCompression.java

    # Step 4: Run the compiled Java code
    - name: Run Java application
      run: java StringCompression
