name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
      name: Run Terraform
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Set up terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.5.0

        - name: setup awscli
          uses: hsupu@setup-awscli@v1
          with:
             # these are default values
            install-dir: /usr/local/aws-cli
            bin-dir: /usr/local/bin

        - name: Configure AWS Credentials 
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            echo "AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY is set"

        - name: Initialize terraform
          run: terraform init

        - name: Plan
          run: terraform plan

        - name: Apply configuration
          if: github.ref == 'refs/heads/main'
          run: terraform apply -auto-approve

        - name: Output Bucket Website URL
          run: echo "S3 Bucket Website URL:${{ steps.terraform.outputs.bucket_website_url }}"
           
      
